<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>ServiceRemarkCheck</name>
  <uuid>f40d5844-a05b-442a-8b8d-61865d70ff6e</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the service_Verification of Pensioner is "Positive"
then
	set decision to "Verified" ;

else 
	set decision to "Not Verified";]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
