<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>CalculatePension</name>
  <uuid>31710c22-bc4d-4792-9142-748cc0d9bf3c</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	AvgSalary is not 0
	and ServiceDuration is at least 40 and less than 62
then
	set decision to a new PensionData where
		the Gratuity is (15 * LastSalary * ServiceDuration ) / 26, 
		the MonthlyPension is (AvgSalary * ServiceDuration)/70 ;
else
	set decision to a new PensionData where
		the Gratuity is 0, 
		the MonthlyPension is 0 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
