<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>PensionerServiceVerification</name>
  <uuid>33f89404-71a3-4776-bdc6-0ba367dfdba5</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
     PensionerNationalityCheck  is "Verified"
    and PensionerServiceDOJCheck  is "Verified"
    and PensionerServiceRemark is "Verified"
then
    set decision to "Verified" ;
else
    set decision to "Not Verified" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
