<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>CalculateServiceDuration</name>
  <uuid>7862f73d-960f-4063-80f6-6f3e8483951e</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the DOB of Pensioner is on or after 7/1/1950 and before 6/30/2004 
	and the DOJ of Pensioner is on or after 7/1/1950 and before 6/30/2004 
	and the DOR of Pensioner is on or after <a date> and before <a date>
then
	set decision to <a number> ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
