<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>ServiceRemarkCheck</name>
  <uuid>7617a311-3a54-41c0-ad54-418e6a440cc2</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    the service_Verification of Pensioner is "Positive"
then
    set decision to "Verified" ;

else 
    set decision to "Not Verified";
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
